### ISSUE TITLE
Headers to lower case

### ISSUE THREAD

**Issue by ddormer** [metasoarous/semantic-csv#38]
I recently found myself needing and writing a function to make headers a consistent case for key lookups in a CSV I don't have control over. I'm not sure if it's something that fits into the library itself but I'm happy to submit a patch if it sounds useful.

**Comment by ddormer** [comment]
I just noticed issue #26. Perhaps I'll take a look at doing that instead if I have the time.

**Comment by metasoarous** [comment]
I'd be okay with an option for that. I'd even be fine with that being the default, but not without doing a major version bump, since I'd consider it a breaking change. Hoping to do a major bump soon for the transducers support bit have been working on other things.

**Comment by metasoarous** [comment]
Oh didn't see second message. Yeah, more general is better.

**Comment by ddormer** [comment]
I'm going to close this, you can now pass `clojure.string/lower-case` to the `transform-header` key on `mappify`.
