### ISSUE TITLE
Compile for ClojureScript via cljc

### ISSUE THREAD

**Issue by metasoarous** [metasoarous/semantic-csv#45]
We're assuming Clojure 1.7 now anyway to get transducers, so reader conditionals may as well come along for the ride!

For now, we'll probably leave the slurp and spit functions out, since we won't have access to `clojure-csv` from cljs. And async will make things a little weird. But would be nice to eventually offer something in this realm.

**Comment by metasoarous** [comment]
I think the right way to deal with the async side of this is to simply write a `slurp-async` which accepts a callback. The `slurp` function would then only be defined for `clj`. The `spit` function isn't so much affected by whether the actual write is async or not, so that can probably be direclty shared.

**Comment by mahinshaw** [comment]
@metasoarous Are you expecting slurp async to run inside a future?  That would be the simplest solution.  Core async is nice for this kind of thing, especially since we now have transducers, which can be added to a channel. However, that being a dependency might be a little much for many people, and a simple future may be a good idea.

**Comment by metasoarous** [comment]
Dude! You're awesome! I had a branch WIP on this bug I guess you beat me to it.

ClojureScript doesn't have `future` unfortunately. I agree that `core.async` would be nice for this, but I'd rather not have the dependency. It's easy enough to use a callback that puts to a go chan. The only downside is backpressure. But slurp is designed to return a single collection, so backpressure isn't as much of a concern. The _real_ nice thing would be using `core.async` to process the rows separately and either run a callback or place each row on a channel to do whatever with, thus applying backpressure and letting one work with big files or "infiinite" streams. Maybe it's better to just say that if you want this you just need to use the use the trandsucers library and use `pipeline`? If there's something we can do to wrap things up a little more elegantly though that would be nice. Maybe what we could do is make it so the `core.async` lib is option, and the `slurp-pipe` or whatever function only gets defined if `core.async` is available. Posh does this actually to make it's Reagent state plugin optional. We could follow suit?

I'll take a look at your PR later today. Any chance you have gotten tests for Cljs working or would be into doing that? That's actually where I got stuck when I tried to bang this out a few months ago. My goal is to push an alpha out in the next couple days. I guess it's fine to do that even without the tests if it's just alpha. But it would be nice to get them before going into full `0.2.0`.

Again; thanks for getting the ball moving on this!

**Comment by mahinshaw** [comment]
I didn't do any tests, as the functionality is the same.  However, I could but the tests, minus the file tests in a cljc, and use cljs.test.  That would make things a little nicer probably.

As far as the core async bit goes.  We could add a seperate namespace that leverages core.async, but mark the dependency as provided (or put it in dev deps).  Then we make sure it is known that you have to import core.async explicitly. It honestly wouldn't be a lot of code considering the ability to leverage transducers on a channel.

And you are welcome. I meant to do it weeks ago, but I have been busy at work. I had some time this afternoon and was able to get the ball rolling.

**Comment by metasoarous** [comment]
I'll open up some additional issues for testing, `slurp-pipe`, `slurp-async`, etc. Ostensibly, the base set of requirements here have been fulfilled.
