### ISSUE TITLE
New transducers/spit-csv is broken

### ISSUE THREAD

**Issue by metasoarous** [metasoarous/semantic-csv#47]
@mahinshaw The tests are failing for `transducer/spit-csv` now... having a bit of trouble figuring out why. Would you mind taking a look?

BTW, I pushed some changes to the implementation there that tries to compose all of the processing into a single transducer: 7068082. The tests were failing even prior to this though.

**Comment by mahinshaw** [comment]
Sorry about that. I will take a look
