### ISSUE TITLE
Hi, question on whether there are plans to push out a new version yet?

### ISSUE THREAD

**Issue by just3ws** [metasoarous/semantic-csv#49]
I really found the `:transform-header` but was going nuts trying to get it to work. It appears the version on Clojars is really old despite having the same version number as `master`. Any chance of bumping and deploying an updated version? Thanks.

**Comment by metasoarous** [comment]
😞 Yes... sorry. I was hoping to get it out around the new year. But I've been swamped. The hold up has been that there is a bunch of new transducers work that we've got queued up, and a few other things I want to get in for a major version bump. I'll try to put out an alpha in the next week or two.

**Comment by just3ws** [comment]
Thanks, I appreciate that. I am using your library to help with a coding
exercise for a new job. Once I figured out the key was not even being
evaluated I worked around the issue. Thanks, it saved me a bunch of
headaches even with the hunt for the missing transformation. :)

**Comment by metasoarous** [comment]
Awesome! Glad to have helped! Good luck! :-)

**Comment by metasoarous** [comment]
@sbelak @ballPointPenguin @mahinshaw - my hope is to get a `0.2.0-alpha` release out in the next couple of days! I put together a `0.2.0` milestone for things I'd like to include in the final `0.2.0` release. It's okay if not all of these make it in, but it would be nice to get what we can while things are still in alpha. Also, FWIW, I've started using ZenHub.com to organize these issues. Just install the plugin and go to the Board link that shows up at the top of the issues page to see the kanban/board thing. Also, I'll be around on https://gitter.im/metasoarous/semantic-csv if anyone wants to chat.

**Comment by metasoarous** [comment]
Oh.. forgot to mention. I'm in Indonesia (Java) for the next few weeks, in case you see posts from me at 4 in the morning 😀

**Comment by metasoarous** [comment]
@!$#!@#$!@#$ I thought I was just deploying `0.2.0-alpha1` but accidentally deployed `0.2.0` >:-|

Ug... OK. Well anyway... I guess that will live there forever now...

I just _also_ deployed a `0.2.1-alpha1`. I guess the ultimate target now is `0.2.1` as the new release, so we'll just keep hacking on these alphas till we're happy with something :-/



Maybe
