### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by agriffis** [metasoarous/semantic-csv#60]
Is this library still under development? Last commit was over a year ago. Last release was an alpha release. No judgment or criticism intended--just trying to figure out whether it's wise to use semantic-csv in a new project or not.

**Comment by metasoarous** [comment]
The reason that the last release is still in alpha is that I wanted to be able to update the documentation properly before creating an official release, but #59 has prevented me from doing this. It has been too long though... if there hasn't been any progress on fixing marginalia, we should probably just look at using some other documentation system (though I am quite fond of the marginalia docs).

As far as the lack of updates, things are more or less stable and working for folks as far as I can tell. There are some new features and various improvements in the alpha release, and there haven't been any issues preventing that from moving out of alpha other than the docs. It's my intent to continue supporting semantic-csv, and I've been lucky to have a number of contributors step up and help with new features, minor improvements and bug fixes in the past, and expect that as the need arises this will continue to be the case. So, I'd highly encourage you to try out the alpha and let us know if you have any issues.

**Comment by agriffis** [comment]
Thanks @metasoarous !
