### ISSUE TITLE
reads pdf files without errors

### ISSUE THREAD

**Issue by iku000888** [metasoarous/semantic-csv#69]
Just wanted to clarify if it is a wontfix. Tested with https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwiS68eHqtXoAhUCJKwKHVsdBEQQFjAAegQIBRAB&url=https%3A%2F%2Fwww.uscis.gov%2Fsystem%2Ffiles_force%2Ffiles%2Fform%2Fi-864-pc.pdf%3Fdownload%3D1&usg=AOvVaw0e6nfkkBM2ozKOqWJSg_aO

```clojure
(semantic-csv.core/slurp-csv "i-864-pc.pdf")
=> 
({:%PDF-1.7
%���� "2 0 obj"}
 {:%PDF-1.7
%���� "<</Filter/FlateDecode/Length 3312>>stream"}
 {:%PDF-1.7
%����
  "[N]���\b�E�/'@��4<'�;�8��������r�Xtefo$PR��0ӥ?kh��h��/��M��._q$ne���]�^�H\\s-C�6տ.[�٥���lB�\"�`I!�׵.���|���ӗ��z�[˒�~E{8��>�\\阣��$�bp��\bRl��G�E\b���_��~EpQ��bU��"}
 {:%PDF-1.7
%����
  "㭥�a_�~ߕ�60��A�j����M�$�X��*�3˒���WI���B�x������l�cd��unRdk��z�&x�w�Y��[���E*F�C����#PvPS 8������sZ\\�j���LW�Qѯ�<�!��G�u�����)��E�\b��n"}
```

**Comment by metasoarous** [comment]
LOL; Yeah, I don't think there's much I can do here, unless you have a particular suggestion. Thanks for reporting though :-)
